window.bibleData = {
  books: [
    { id: "genesis", name: "창세기", testament: "OT",
      titles: [
        "천지 창조",
        "인간 창조와 에덴동산",
        "죄의 기원과 인류의 타락",
        "가인과 아벨 및 인간 문명의 시작",
        "아담으로부터 노아까지의 계보",
        "홍수 심판의 예고와 노아의 방주",
        "대홍수 심판",
        "홍수의 멈춤과 지면의 회복",
        "무지개 언약과 노아의 실수",
        "노아 아들들의 후예와 인류의 확산",
        "바벨탑 사건과 인류의 분산",
        "아브람의 소명 및 사래 사건",
        "아브람과 롯의 분리",
        "가나안 전쟁과 살렘 왕 멜기세덱",
        "아브람과 맺은 하나님의 횃불 언약",
        "하갈과 이스마엘",
        "아브람의 개명과 언약의 표징-할례",
        "세 천사의 방문과 아브라함의 중보",
        "소돔과 고모라의 멸망",
        "아브라함과 그랄 왕 아비멜렉",
        "이삭의 출생과 이스마엘의 축출",
        "아브라함에게 임한 하나님의 시험",
        "사라의 죽음과 매장지 막벨라 굴",
        "이삭과 리브가의 결혼",
        "아브라함의 죽음과 이삭의 두 아들",
        "리브가 사건과 이삭의 우물",
        "이삭에게 축복 받은 야곱",
        "야곱의 도피와 사닥다리 환상",
        "야곱의 결혼과 그의 처가살이",
        "야곱의 자녀와 그의 번성",
        "야곱의 귀향과 미스바 언약",
        "야곱의 얍복 강 씨름",
        "야곱과 에서의 재회와 화해",
        "디나 강간 사건과 세겜성 노략",
        "벧엘로 올라가 제단을 쌓은 야곱",
        "에서 곧 에돔의 후손들",
        "요셉의 꿈과 애굽으로 팔려간 요셉",
        "유다와 다말 사건",
        "보디발 아내의 유혹과 요셉의 고난",
        "바로의 두 관원장과 요셉의 꿈 해석",
        "바로의 꿈과 애굽 총리가 된 요셉",
        "곡식을 구하러 온 요셉의 형제들",
        "요셉 형제들의 두 번째 애굽 방문",
        "요셉의 은잔 시험과 유다의 탄원",
        "자신의 신분을 밝히는 요셉",
        "야곱 가족의 애굽 이주",
        "애굽에 정착한 하나님의 선민",
        "요셉의 두 아들을 축복하는 야곱",
        "열 두 아들에 대한 야곱의 예언",
        "야곱의 장례식과 요셉의 죽음"
      ] },
    { id: "exodus", name: "출애굽기", testament: "OT",
      titles: [
        "이스라엘 민족의 번성과 노예 생활",
        "모세의 출생과 미디안 도피 생활",
        "모세의 소명",
        "여호와의 표징과 모세의 애굽 귀환",
        "모세의 해방 요구와 바로의 핍박",
        "하나님의 위로와 모세의 가문",
        "모세와 바로의 대결-피 재앙",
        "개구리․이․파리 재앙",
        "악질․독종․우박 재앙",
        "메뚜기와 흑암 재앙",
        "마지막 열 번째 재앙의 경고",
        "유월절 예식과 출애굽",
        "초 태생 규례 및 불기둥과 구름 기둥",
        "홍해 도하",
        "감사와 승리의 찬양",
        "만나와 메추라기",
        "르비딤 물 사건과 아말렉 전쟁",
        "이드로의 방문과 조언",
        "시내 산에 강림하신 여호와",
        "십계명",
        "종․살인․폭력․배상 등에 관한 법",
        "절도․담보․간음 등에 관한 법",
        "재판․안식․절기 등에 관한 법",
        "여호와의 백성간의 언약 체결",
        "성소와 성물들-법궤․떡상․금등대",
        "성막의 양식",
        "번제단과 성막 뜰의 모형",
        "제사장의 거룩한 옷",
        "제사장 위임식 규례와 상번제",
        "분향단․물두멍․관유․향 제조법",
        "성막 건축의 담당자와 안식일 규례",
        "금송아지 숭배 사건",
        "모세의 중보 기도와 하나님의 영광",
        "두 번째 십계명 돌비와 갱신된 언약",
        "성막 건축 재료와 백성들의 헌물",
        "성막 건축",
        "성막 제작-법궤․떡상․등대․분향단",
        "성막 뜰의 기구들과 총 성막 재료",
        "제사장 의복 제작과 성막 준공",
        "성막 봉헌식"
      ] },
    { id: "leviticus", name: "레위기", testament: "OT", titles: [] },
    { id: "numbers", name: "민수기", testament: "OT", titles: [] },
    { id: "deuteronomy", name: "신명기", testament: "OT", titles: [] },
    { id: "joshua", name: "여호수아", testament: "OT", titles: [] },
    { id: "judges", name: "사사기", testament: "OT", titles: [] },
    { id: "ruth", name: "룻기", testament: "OT", titles: [] },
    { id: "samuel1", name: "사무엘상", testament: "OT", titles: [] },
    { id: "samuel2", name: "사무엘하", testament: "OT", titles: [] },
    { id: "kings1", name: "열왕기상", testament: "OT", titles: [] },
    { id: "kings2", name: "열왕기하", testament: "OT", titles: [] },
    { id: "chronicles1", name: "역대상", testament: "OT", titles: [] },
    { id: "chronicles2", name: "역대하", testament: "OT", titles: [] },
    { id: "ezra", name: "에스라", testament: "OT", titles: [] },
    { id: "nehemiah", name: "느헤미야", testament: "OT", titles: [] },
    { id: "esther", name: "에스더", testament: "OT", titles: [] },
    { id: "job", name: "욥기", testament: "OT", titles: [] },
    { id: "psalms1", name: "시편 1권", testament: "OT", startChapter: 1, titles: [] },
    { id: "psalms2", name: "시편 2권", testament: "OT", startChapter: 42,
      titles: [
        "하나님을 향한 갈망",
        "시온을 향한 소망",
        "고난에 직면한 이스라엘의 탄원",
        "왕의 결혼을 축하하는 노래",
        "시온을 보호하시는 하나님의 손길",
        "하나님의 우주적 왕권에 대한 찬양",
        "하나님이 거하시는 시온의 영광",
        "세속적 이익과 번영의 허무",
        "참된 예배의 본질",
        "참회의 기도",
        "강포한 자의 궁극",
        "어리석은 무신론자",
        "하나님의 구원을 확신하는 믿음",
        "배신당한 자의기도",
        "어둠 속에서도 비취는 주의 빛",
        "찬양으로 승리하는 신앙",
        "不法者들을 고발하는 시",
        "방패와 피난처 되시는 하나님",
        "승리를 탄원하는 기도",
        "땅 끝에서의 부르짖음",
        "진정 의지해야 할 대상",
        "광야에서의 기도",
        "악행과 그 결과",
        "하나님의 은총에 대한 찬양",
        "만유의 주,곧 나의 주",
        "만방에 선포하는 주의 구원",
        "승리케 하시는 하나님",
        "역경에 대한 탄원",
        "구원을 간구 하는 기도",
        "노년의 기도",
        "이상적 통치에 대한 간구와 기원"
      ] },
    { id: "psalms3", name: "시편 3권", testament: "OT", startChapter: 73, titles: [] },
    { id: "psalms4", name: "시편 4권", testament: "OT", startChapter: 90, titles: [] },
    { id: "psalms5", name: "시편 5권", testament: "OT", startChapter: 107, titles: [] },
    { id: "proverbs", name: "잠언", testament: "OT", titles: [] },
    { id: "ecclesiastes", name: "전도서", testament: "OT", titles: [] },
    { id: "songofsolomon", name: "아가", testament: "OT", titles: [] },
    { id: "isaiah", name: "이사야", testament: "OT", titles: [] },
    { id: "jeremiah", name: "예레미야", testament: "OT", titles: [] },
    { id: "lamentations", name: "예레미야 애가", testament: "OT", titles: [] },
    { id: "ezekiel", name: "에스겔", testament: "OT", titles: [] },
    { id: "daniel", name: "다니엘", testament: "OT", titles: [] },
    { id: "hosea", name: "호세아", testament: "OT", titles: [] },
    { id: "joel", name: "요엘", testament: "OT", titles: [] },
    { id: "amos", name: "아모스", testament: "OT", titles: [] },
    { id: "obadiah", name: "오바댜", testament: "OT", titles: [] },
    { id: "jonah", name: "요나", testament: "OT", titles: [] },
    { id: "micah", name: "미가", testament: "OT", titles: [] },
    { id: "nahum", name: "나훔", testament: "OT", titles: [] },
    { id: "habakkuk", name: "하박국", testament: "OT", titles: [] },
    { id: "zephaniah", name: "스바냐", testament: "OT", titles: [] },
    { id: "haggai", name: "학개", testament: "OT", titles: [] },
    { id: "zechariah", name: "스가랴", testament: "OT", titles: [] },
    { id: "malachi", name: "말라기", testament: "OT", titles: [] },
    { id: "matthew", name: "마태복음", testament: "NT",
      titles: [
        "예수의 족보와 탄생 과정",
        "메시야 탄생에 대한 반응과 유년 시절",
        "메시야를 위한 두 증언",
        "시험 승리와 공생애의 개시",
        "메시야 왕국의 새로운 기준",
        "천국 시민의 새 생활",
        "천국에 들어가는 길",
        "질병과 자연을 다스리시는 왕의 권능",
        "죄인과 병자를 치유하시는 왕의 권능",
        "전도자의 자세와 각오",
        "배척받으신 메시야의 질책과 권유",
        "바리새인들의 메시야 배척",
        "천국에 관한 비유들",
        "이적적 권능과 고조되는 핍박Ⅰ",
        "이적적 권능과 고조되는 핍박Ⅱ",
        "메시야의 자기 공개",
        "예수의 영화로우신 변형",
        "천국 시민의 윤리관",
        "천국 시민의 생활 규범과 영생의 조건",
        "천국의實相에 관한 교훈",
        "예루살렘에 당도하신 메시야",
        "혼인 잔치 비유와 일련의 질문들",
        "종교 지도자들에 관한 경고",
        "역사의 종말에 대한 예언",
        "종말을 예비하는 자의 자세",
        "메시야의 최후 만찬",
        "메시야의 수난과 죽음",
        "부활하신 예수"
      ] },
    { id: "mark", name: "마가복음", testament: "NT",
      titles: [
        "종의 출현",
        "종에 대한 핍박의 대두",
        "확장되는 종의 사역과 고조되는 핍박",
        "종의 비유",
        "종의 권능",
        "핍박의 고조 및 종의 사역의 확장",
        "종의 이방 사역",
        "종의 신분과 사역의 공개",
        "종의 수난과 영광에 대한 거듭되는 경고",
        "예루살렘으로 향하시는 종",
        "종의 예루살렘 입성",
        "가열되는 음모와 종의 대응",
        "종의 감람산 강화",
        "체포당하시는 종",
        "십자가상의 종",
        "종의 부활"
      ] },
    { id: "luke", name: "누가복음", testament: "NT", titles: [] },
    { id: "john", name: "요한복음", testament: "NT", titles: [] },
    { id: "acts", name: "사도행전", testament: "NT", titles: [] },
    { id: "romans", name: "로마서", testament: "NT", titles: [] },
    { id: "corinthians1", name: "고린도전서", testament: "NT", titles: [] },
    { id: "corinthians2", name: "고린도후서", testament: "NT", titles: [] },
    { id: "galatians", name: "갈라디아서", testament: "NT", titles: [] },
    { id: "ephesians", name: "에베소서", testament: "NT", titles: [] },
    { id: "philippians", name: "빌립보서", testament: "NT", titles: [] },
    { id: "colossians", name: "골로새서", testament: "NT", titles: [] },
    { id: "thessalonians1", name: "데살로니가전서", testament: "NT", titles: [] },
    { id: "thessalonians2", name: "데살로니가후서", testament: "NT", titles: [] },
    { id: "timothy1", name: "디모데전서", testament: "NT", titles: [] },
    { id: "timothy2", name: "디모데후서", testament: "NT", titles: [] },
    { id: "titus", name: "디도서", testament: "NT", titles: [] },
    { id: "philemon", name: "빌레몬서", testament: "NT", titles: [] },
    { id: "hebrews", name: "히브리서", testament: "NT", titles: [] },
    { id: "james", name: "야고보서", testament: "NT", titles: [] },
    { id: "peter1", name: "베드로전서", testament: "NT", titles: [] },
    { id: "peter2", name: "베드로후서", testament: "NT", titles: [] },
    { id: "john1", name: "요한일서", testament: "NT", titles: [] },
    { id: "john2", name: "요한이서", testament: "NT", titles: [] },
    { id: "john3", name: "요한삼서", testament: "NT", titles: [] },
    { id: "jude", name: "유다서", testament: "NT", titles: [] },
    { id: "revelation", name: "요한계시록", testament: "NT", titles: [] }
  ]
};
