window.bibleData = {
  books: [
    { id: "genesis", name: "창세기", testament: "OT",
      titles: [
        "천지 창조",
        "인간 창조와 에덴동산",
        "죄의 기원과 인류의 타락",
        "가인과 아벨 및 인간 문명의 시작",
        "아담으로부터 노아까지의 계보",
        "홍수 심판의 예고와 노아의 방주",
        "대홍수 심판",
        "홍수의 멈춤과 지면의 회복",
        "무지개 언약과 노아의 실수",
        "노아 아들들의 후예와 인류의 확산",
        "바벨탑 사건과 인류의 분산",
        "아브람의 소명 및 사래 사건",
        "아브람과 롯의 분리",
        "가나안 전쟁과 살렘 왕 멜기세덱",
        "아브람과 맺은 하나님의 횃불 언약",
        "하갈과 이스마엘",
        "아브람의 개명과 언약의 표징-할례",
        "세 천사의 방문과 아브라함의 중보",
        "소돔과 고모라의 멸망",
        "아브라함과 그랄 왕 아비멜렉",
        "이삭의 출생과 이스마엘의 축출",
        "아브라함에게 임한 하나님의 시험",
        "사라의 죽음과 매장지 막벨라 굴",
        "이삭과 리브가의 결혼",
        "아브라함의 죽음과 이삭의 두 아들",
        "리브가 사건과 이삭의 우물",
        "이삭에게 축복 받은 야곱",
        "야곱의 도피와 사닥다리 환상",
        "야곱의 결혼과 그의 처가살이",
        "야곱의 자녀와 그의 번성",
        "야곱의 귀향과 미스바 언약",
        "야곱의 얍복 강 씨름",
        "야곱과 에서의 재회와 화해",
        "디나 강간 사건과 세겜성 노략",
        "벧엘로 올라가 제단을 쌓은 야곱",
        "에서 곧 에돔의 후손들",
        "요셉의 꿈과 애굽으로 팔려간 요셉",
        "유다와 다말 사건",
        "보디발 아내의 유혹과 요셉의 고난",
        "바로의 두 관원장과 요셉의 꿈 해석",
        "바로의 꿈과 애굽 총리가 된 요셉",
        "곡식을 구하러 온 요셉의 형제들",
        "요셉 형제들의 두 번째 애굽 방문",
        "요셉의 은잔 시험과 유다의 탄원",
        "자신의 신분을 밝히는 요셉",
        "야곱 가족의 애굽 이주",
        "애굽에 정착한 하나님의 선민",
        "요셉의 두 아들을 축복하는 야곱",
        "열 두 아들에 대한 야곱의 예언",
        "야곱의 장례식과 요셉의 죽음"
      ] },
    { id: "exodus", name: "출애굽기", testament: "OT",
      titles: [
        "이스라엘 민족의 번성과 노예 생활",
        "모세의 출생과 미디안 도피 생활",
        "모세의 소명. 호렙산 불꽃",
        "여호와의 표징과 모세의 애굽 귀환",
        "모세의 해방 요구와 바로의 핍박",
        "하나님의 위로와 모세의 가문",
        "모세와 바로의 대결-피 재앙",
        "개구리․이․파리 재앙",
        "악질․독종․우박 재앙",
        "메뚜기와 흑암 재앙",
        "마지막 열 번째 재앙의 경고",
        "유월절 예식과 출애굽",
        "초 태생 규례 및 불기둥과 구름 기둥",
        "홍해 도하",
        "감사와 승리의 찬양",
        "만나와 메추라기",
        "르비딤 물 사건과 아말렉 전쟁",
        "이드로의 방문과 조언",
        "시내 산에 강림하신 여호와",
        "십계명",
        "종․살인․폭력․배상 등에 관한 법",
        "절도․담보․간음 등에 관한 법",
        "재판․안식․절기 등에 관한 법",
        "여호와의 백성간의 언약 체결",
        "성소와 성물들-법궤․떡상․금등대",
        "성막의 양식",
        "번제단과 성막 뜰의 모형",
        "제사장의 거룩한 옷",
        "제사장 위임식 규례와 상번제",
        "분향단․물두멍․관유․향 제조법",
        "성막 건축의 담당자와 안식일 규례",
        "금송아지 숭배 사건",
        "모세의 중보 기도와 하나님의 영광",
        "두 번째 십계명 돌비와 갱신된 언약",
        "성막 건축 재료와 백성들의 헌물",
        "성막 건축",
        "성막 제작-법궤․떡상․등대․분향단",
        "성막 뜰의 기구들과 총 성막 재료",
        "제사장 의복 제작과 성막 준공",
        "성막 봉헌식"
      ] },
    { id: "leviticus", name: "레위기", testament: "OT", titles: [] },
    { id: "numbers", name: "민수기", testament: "OT", titles: [] },
    { id: "deuteronomy", name: "신명기", testament: "OT", titles: [] },
    { id: "joshua", name: "여호수아", testament: "OT", titles: [] },
    { id: "judges", name: "사사기", testament: "OT", titles: [] },
    { id: "ruth", name: "룻기", testament: "OT", titles: [] },
    { id: "samuel1", name: "사무엘상", testament: "OT", titles: [] },
    { id: "samuel2", name: "사무엘하", testament: "OT", titles: [] },
    { id: "kings1", name: "열왕기상", testament: "OT", titles: [] },
    { id: "kings2", name: "열왕기하", testament: "OT", titles: [] },
    { id: "chronicles1", name: "역대상", testament: "OT", titles: [] },
    { id: "chronicles2", name: "역대하", testament: "OT", titles: [] },
    { id: "ezra", name: "에스라", testament: "OT", titles: [] },
    { id: "nehemiah", name: "느헤미야", testament: "OT", titles: [] },
    { id: "esther", name: "에스더", testament: "OT", titles: [] },
    { id: "job", name: "욥기", testament: "OT", titles: [] },
    { id: "psalms1", name: "시편 1권", testament: "OT", startChapter: 1, titles: [] },
    { id: "psalms2", name: "시편 2권", testament: "OT", startChapter: 42,
      titles: [
        "하나님을 향한 갈망",
        "시온을 향한 소망",
        "고난에 직면한 이스라엘의 탄원",
        "왕의 결혼을 축하하는 노래",
        "시온을 보호하시는 하나님의 손길",
        "하나님의 우주적 왕권에 대한 찬양",
        "하나님이 거하시는 시온의 영광",
        "세속적 이익과 번영의 허무",
        "참된 예배의 본질",
        "참회의 기도",
        "강포한 자의 궁극",
        "어리석은 무신론자",
        "하나님의 구원을 확신하는 믿음",
        "배신당한 자의기도",
        "어둠 속에서도 비취는 주의 빛",
        "찬양으로 승리하는 신앙",
        "不法者들을 고발하는 시",
        "방패와 피난처 되시는 하나님",
        "승리를 탄원하는 기도",
        "땅 끝에서의 부르짖음",
        "진정 의지해야 할 대상",
        "광야에서의 기도",
        "악행과 그 결과",
        "하나님의 은총에 대한 찬양",
        "만유의 주,곧 나의 주",
        "만방에 선포하는 주의 구원",
        "승리케 하시는 하나님",
        "역경에 대한 탄원",
        "구원을 간구 하는 기도",
        "노년의 기도",
        "이상적 통치에 대한 간구와 기원"
      ] },
    { id: "psalms3", name: "시편 3권", testament: "OT", startChapter: 73, titles: [] },
    { id: "psalms4", name: "시편 4권", testament: "OT", startChapter: 90, titles: [] },
    { id: "psalms5", name: "시편 5권", testament: "OT", startChapter: 107, titles: [] },
    { id: "proverbs", name: "잠언", testament: "OT", titles: [] },
    { id: "ecclesiastes", name: "전도서", testament: "OT", titles: [] },
    { id: "songofsolomon", name: "아가", testament: "OT", titles: [] },
    { id: "isaiah", name: "이사야", testament: "OT", titles: [] },
    { id: "jeremiah", name: "예레미야", testament: "OT", titles: [] },
    { id: "lamentations", name: "예레미야 애가", testament: "OT", titles: [] },
    { id: "ezekiel", name: "에스겔", testament: "OT", titles: [] },
    { id: "daniel", name: "다니엘", testament: "OT", titles: [] },
    { id: "hosea", name: "호세아", testament: "OT", titles: [] },
    { id: "joel", name: "요엘", testament: "OT", titles: [] },
    { id: "amos", name: "아모스", testament: "OT", titles: [] },
    { id: "obadiah", name: "오바댜", testament: "OT", titles: [] },
    { id: "jonah", name: "요나", testament: "OT", titles: [] },
    { id: "micah", name: "미가", testament: "OT", titles: [] },
    { id: "nahum", name: "나훔", testament: "OT", titles: [] },
    { id: "habakkuk", name: "하박국", testament: "OT", titles: [] },
    { id: "zephaniah", name: "스바냐", testament: "OT", titles: [] },
    { id: "haggai", name: "학개", testament: "OT", titles: [] },
    { id: "zechariah", name: "스가랴", testament: "OT", titles: [] },
    { id: "malachi", name: "말라기", testament: "OT", titles: [] },
    { id: "matthew", name: "마태복음", testament: "NT",
      titles: [
        "예수님의 족보",
        "탄생과 동방박사 경배",
        "세례 받으심",
        "시험을 받으심",
        "산상설교(8복)",
        "산상설교(주기도)",
        "산상설교(좁은 문)",
        "백부장의 종을 고치심",
        "마태를 부르심",
        "12제자 택하심",
        "세례요한의 질문",
        "밀이삭(안식일)",
        "여덟 가지의 비유",
        "5천 명 먹이심(요한 순교)",
        "4천 명 먹이심",
        "베드로의 신앙고백",
        "산상변화",
        "어린아이(범죄와 용서)",
        "젊은 부자(이혼과 영생)",
        "포도원의 삯꾼",
        "예루살렘 입성과 청결",
        "혼인잔치의 비유",
        "일곱 가지 화",
        "말세와 예수님의 예언",
        "열 처녀 비유",
        "최후의 만찬(겟세마네)",
        "십자가에 달리심",
        "예수님의 부활"
      ] },
    { id: "mark", name: "마가복음", testament: "NT",
      titles: [
        "세례요한",
        "마태를 부르심",
        "12제자 택하심",
        "하나님 나라 비유(풍랑)",
        "병 고침과 악귀 추방",
        "5천 명 먹이심",
        "손 씻는 문제와 기적(수로보니게)",
        "4천 명 먹이심",
        "산상변화",
        "젊은 부자의 고민",
        "예루살렘 입성(호산나)",
        "악한 농부(큰 계명)",
        "말세와 재림",
        "유월절(성만찬과 감람산, 잡히심)",
        "십자가에 달리심(재판)",
        "부활과 승천"
      ] },
    { id: "luke", name: "누가복음", testament: "NT",
      titles: [
        "세례요한과 예수님 탄생 예고",
        "예수님의 탄생",
        "예수님의 족보",
        "시험을 이기심",
        "3제자 부르심과 기적(중풍병)",
        "12제자 택하심(설교)",
        "백부장의 종을 고치심",
        "거라사의 악귀(씨 뿌림 비유)",
        "5천 명(제자 파송)",
        "70인의 파송",
        "기도와 교훈",
        "미련한 부자",
        "3가지의 비유(회개의 경고)",
        "안식문제(큰 잔치 비유)",
        "돌아온 탕자",
        "부자와 나사로",
        "열 문둥이",
        "불의한 재판관(합당한 기도)",
        "삭개오의 회개",
        "악한 농부와 질문과 답",
        "말세와 예수의 재림",
        "최후의 만찬과 잡히심",
        "십자가에 달리심",
        "부활과 승천"
      ] },
    { id: "john", name: "요한복음", testament: "NT",
      titles: [
        "말씀 (독생자의 탄생)",
        "포도주의 이적 (가나)",
        "중생과 하나님의 사랑",
        "예수님과 사마리아 여인 (생수)",
        "베데스다 못의 기적",
        "생명의 떡 (5천 명)",
        "장막절의 교훈 (생명수)",
        "빛과 자유 (간음여인)",
        "실로암 못 (소경)",
        "선한 목자이신 예수",
        "나사로의 부활",
        "호산나 (영광)",
        "만찬과 발 씻기심",
        "제자들을 위로하심",
        "포도나무의 비유",
        "보혜사 성령",
        "최후의 기도",
        "잡히심과 심문 당하심",
        "십자가에 달리심",
        "부활과 나타나심",
        "예수님과 베드로의 문답"
      ] },
    { id: "acts", name: "사도행전", testament: "NT",
      titles: [
        "승천",
        "미문 앞의 앉은뱅이",
        "아나니아와 삽비라",
        "스데반의 설교와 순교",
        "사울의 회개",
        "복음이 이방인에게 (베드로의 변명)",
        "바울의 1차 전도여행",
        "예루살렘의 공의회 (바울 2차 전도여행)",
        "베뢰아와 아덴에 전도",
        "바울이 에베소에서 기적 행함",
        "환난 당하는 바울",
        "가이사라로 호송된 바울",
        "베스도가 바울을 심문",
        "로마로 호송 (파선)",
        "5순절 성령 강림",
        "베드로와 요한의 갇힘",
        "일곱 집사를 세움",
        "사마리아와 유대 전도 (내시)",
        "고넬료에게 나타난 성령",
        "야고보의 순교와 베드로의 갇힘",
        "쓰스와 허메",
        "바울이 디모데를 만남",
        "바울이 2차 전도에서 돌아옴",
        "바울의 3차 전도여행",
        "바울의 설교와 민중의 반박",
        "벨릭스 앞에 선 바울",
        "아그립바 왕 앞에 선 바울",
        "로마에 도착한 바울"
      ] },
    { id: "romans", name: "로마서", testament: "NT", titles: [] },
    { id: "corinthians1", name: "고린도전서", testament: "NT", titles: [] },
    { id: "corinthians2", name: "고린도후서", testament: "NT", titles: [] },
    { id: "galatians", name: "갈라디아서", testament: "NT", titles: [] },
    { id: "ephesians", name: "에베소서", testament: "NT", titles: [] },
    { id: "philippians", name: "빌립보서", testament: "NT", titles: [] },
    { id: "colossians", name: "골로새서", testament: "NT", titles: [] },
    { id: "thessalonians1", name: "데살로니가전서", testament: "NT", titles: [] },
    { id: "thessalonians2", name: "데살로니가후서", testament: "NT", titles: [] },
    { id: "timothy1", name: "디모데전서", testament: "NT", titles: [] },
    { id: "timothy2", name: "디모데후서", testament: "NT", titles: [] },
    { id: "titus", name: "디도서", testament: "NT", titles: [] },
    { id: "philemon", name: "빌레몬서", testament: "NT", titles: [] },
    { id: "hebrews", name: "히브리서", testament: "NT", titles: [] },
    { id: "james", name: "야고보서", testament: "NT", titles: [] },
    { id: "peter1", name: "베드로전서", testament: "NT", titles: [] },
    { id: "peter2", name: "베드로후서", testament: "NT", titles: [] },
    { id: "john1", name: "요한일서", testament: "NT", titles: [] },
    { id: "john2", name: "요한이서", testament: "NT", titles: [] },
    { id: "john3", name: "요한삼서", testament: "NT", titles: [] },
    { id: "jude", name: "유다서", testament: "NT", titles: [] },
    { id: "revelation", name: "요한계시록", testament: "NT", titles: [] }
  ]
};
